# Generated by Django 5.2.4 on 2025-07-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_progress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={},
        ),
        migrations.RemoveField(
            model_name='module',
            name='order',
        ),
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(default='Нет описания'),
            preserve_default=False,
        ),
    ]
