# Generated by Django 5.2.4 on 2025-07-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_quizattempt_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='attempts',
            field=models.ManyToManyField(blank=True, related_name='results', to='courses.quizattempt'),
        ),
    ]
